# Generated by Django 2.1.5 on 2019-01-27 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boilerroomyoutube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='channelId',
            field=models.TextField(default='0', verbose_name='channelId'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='etag',
            field=models.TextField(default='sample_etag', verbose_name='etag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='published_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='title',
            field=models.TextField(default='sample_title', verbose_name='title'),
            preserve_default=False,
        ),
    ]
