# Generated by Django 2.1.5 on 2019-01-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boilerroomyoutube', '0002_auto_20190127_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideo',
            name='channelId',
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='channel_id',
            field=models.TextField(default='0', verbose_name='channel_id'),
            preserve_default=False,
        ),
    ]
